import numpy as np
import os
import sklearn
import matplotlib.pyplot as plt
import scipy.stats as stats
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
import torch
import torch.nn as nn

def load_data():
  X =np.load('data2D.npy')
  valid_batch = int(len(X) / 4.0)
  np.random.seed(45689)
  rnd_idx = np.arange(len(X))
  np.random.shuffle(rnd_idx)
  val_data = X[rnd_idx[:valid_batch]]
  train_data = X[rnd_idx[valid_batch:]]
  
  return train_data, val_data

def train_kmean_torch(train_data, k = 5, lr=0.1, epoch=150):
  #Define a cluster
  m = torch.rand((k, train_data.shape[1]), requires_grad=True)
  
  #Convert training data to a torch tensor
  X_train = torch.from_numpy(train_data).float()

  #TODO: define the Adam Optimizer
  optimizer = torch.optim.Adam([m], lr=lr)

  for epoch in range(epoch):
    list_mse = []
    for i in range(k):
      #TODO: fill in the append function
      list_mse.append(torch.sum((X_train - m[i]) ** 2, dim=1))

    #TODO: calculate the loss function. Complete the 
    #below 3 lines. 
    list_mse_torch = torch.stack(list_mse)  #Stacks the list_mse[i]
    list_mse_torch_min,_ = torch.min(list_mse_torch, dim=0)  #Calculate the min 
    L_train = torch.mean(list_mse_torch_min)  #Calculate the mean loss

    #Update the model using optimizer and L_train
    optimizer.zero_grad()
    L_train.backward()
    optimizer.step()

  L_train = L_train.detach().numpy()
  m = m.detach().numpy()

  return L_train, m

def evaluate(test_data, m):
  L_k = np.zeros((len(test_data), len(m)))
  for k in range(len(m)):
    L_k[:, k] = np.sum((test_data - m[k]) ** 2, axis=1)
  return np.mean(np.min(L_k, axis=1))

def get_association(test_data, m):
  #This function returns the list of cluster associated for 
  # each data points.
  num_cluster = len(m)
  N, d = test_data.shape
  L_k = np.zeros((N, num_cluster))

  for k in range(num_cluster):
    #TODO: calculate the distance per cluster
    #by fill in the blank
    L_k[:,k] = np.sum((test_data - m[k]) ** 2, axis=1)
  
  #Assign to the nearest cluster.
  index = np.argmin(L_k, axis = -1)
  index = index.reshape(len(index), 1)
  return index

def test_pytorch(train_data, test_data, k=5):
  L,m = train_kmean_torch(train_data, k)
  index = get_association(test_data, m)
  new_X = np.concatenate((test_data, index), axis = 1)

  score = evaluate(test_data, m)
  print ("PyTorch test score:", score)
  color_list = ['g', 'b', 'm', 'y', 'c']

  for i in range(len(m)):
    tmp = new_X[new_X[...,-1] == i]
    plt.scatter(tmp[:,0], tmp[:,1], c=color_list[i])

  return score

def test_sckitlearn(train_data, test_data, k=5):
  #TODO: Create the KMeans object and fit the model using train_data
  # Use k cluster, 5000 maximum iterations and "auto" algorithm.
  # Fill in the line below.
  kmeans = KMeans(n_clusters=k, max_iter=5000, algorithm="lloyd").fit(train_data)
  
  #Association and visualization step
  index = kmeans.predict(test_data)
  index = index.reshape(len(index), 1)
  new_X = np.concatenate((test_data, index), axis = 1)

  color_list = ['g', 'b', 'm', 'y', 'c']
  score = evaluate(test_data, kmeans.cluster_centers_)
  print ("Scikit-learn test score:", score)
  for i in range(len(kmeans.cluster_centers_)):
    tmp = new_X[new_X[...,-1] == i]
    plt.scatter(tmp[:,0], tmp[:,1], c=color_list[i])

  return score

train_data, test_data = load_data()
output_dir = "report_outputs"
os.makedirs(output_dir, exist_ok=True)

summary_rows = []
for k in range(1, 6):
    print (f"Test scores for k = {k}")

    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    pytorch_score = test_pytorch(train_data, test_data, k)
    plt.title(f"PyTorch clustering (k={k})")
    plt.xlabel("x1")
    plt.ylabel("x2")

    plt.subplot(1, 2, 2)
    sklearn_score = test_sckitlearn(train_data, test_data, k)
    plt.title(f"Scikit-learn clustering (k={k})")
    plt.xlabel("x1")
    plt.ylabel("x2")

    plt.tight_layout()
    fig_path = os.path.join(output_dir, f"kmeans_compare_k{k}.png")
    plt.savefig(fig_path, dpi=200)
    plt.close()

    summary_rows.append((k, pytorch_score, sklearn_score, fig_path))

report_path = os.path.join(output_dir, "kmeans_report.md")
with open(report_path, "w", encoding="utf-8") as f:
  f.write("# K-means Comparison Results\n\n")
  f.write("This file is auto-generated by kmeans.py.\n\n")
  f.write("| k | PyTorch test score | Scikit-learn test score |\n")
  f.write("|---|--------------------|-------------------------|\n")
  for k, pytorch_score, sklearn_score, _ in summary_rows:
    f.write(f"| {k} | {pytorch_score:.6f} | {sklearn_score:.6f} |\n")

  f.write("\n## Figures\n\n")
  for k, _, _, fig_path in summary_rows:
    f.write(f"### k = {k}\n\n")
    f.write(f"![k={k} comparison]({os.path.basename(fig_path)})\n\n")

print(f"Saved report and figures to: {output_dir}")
